---
title: "lab05vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{lab05vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(lab5package)

# getcityid() is a function tells you the id of a municipality in kolada's api
# you can use this id for further useage of using api

# get the id
getcityid("linköping")

# return as a string
id <- getcityid("linköping")
print(id)
class(id)

# case INsensitive
getcityid("StOckHoLm")

# but remember the name of municipality must be correct
getcityid("linkoping")

# and regions
getcityid("region stockholm")


# getcityidlessdata() is a function does things alike getcityid() but GET & stores less data in your own devices
# but not exactly having same function, and getcityid() is more recommended

# get the id
getcityid_lessdata("linköping")

# return as a string
id <- getcityid_lessdata("linköping")
print(id)
class(id)

# case INsensitive
getcityid_lessdata("LINköping")

# but remember the name of municipality must be correct
# >getcityid_lessdata("linkoping")
# Error in getcityid_lessdata("linkoping") : 
#  Oops, notfound. Check is the input correct and a full name

# id of regions will be returned first when it share a same name with a city
# so getcityid is more recommended
getcityid_lessdata("stockholm")
getcityid("region stockholm")
getcityid("stockholm")

```
